apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: pokroetsanebopylinkamizvezd
spec:
  environments:
    - name: production2
      build:
        from: kinda-production2
    - name: dev
      build:
        from: master
  components:
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3000
      public: false
      environmentConfig:
        - environment: production2
          variables:
            PORT: 3000
            NODE_ENV: "production2"
          monitoring: true
          resources:
            requests:
              memory: "42Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
          replicas: 1
        - environment: dev
          variables:
            PORT: 3000
            NODE_ENV: "dev"
          monitoring: true
          resources:
            requests:
              memory: "42Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
          replicas: 1
      secrets:
      - MY_SUPER_SECRET
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3001
      public: true
      environmentConfig:
        - environment: production2
          variables:
            PORT: 3001
            NODE_ENV: "production"
            ECHO_URL: "http://echo:3000"
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "does this name matter"
            ECHO_URL: "http://echo:3000"
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
  dnsAppAlias:
    environment: production2
    component: www
